### ISSUE TITLE
Migrate WebBase wiki from Google Code

### ISSUE THREAD

**Issue by atifaziz** [elmah/www#13]
Migrate [WebBase wiki from Google Code](https://code.google.com/p/elmah/wiki/WebBase).

**Comment by fiftynineseconds** [comment]
I can do this.

**Comment by atifaziz** [comment]
@fiftynineseconds I've already started work on this one; just haven't pushed it as I'm still not done. I should have assigned this to myself so sorry to mislead that this was up for grabs. However, there's [plenty more to pick from](https://code.google.com/p/elmah/w/list). I'll let you choose and [open it as an issue](https://github.com/elmah/www/issues/new). Just make sure, it's not [already done](https://elmah.github.io/a/). Thanks!

**Comment by fiftynineseconds** [comment]
Great. Thanks!
