### ISSUE TITLE
Documentation on compiling 2.0 code base

### ISSUE THREAD

**Issue by atifaziz** [elmah/www#28]
Migrated from elmah/Elmah#352

> The [Compiling](https://elmah.github.io/a/compiling/) wiki page is out of date. It states that Visual Studio solutions are available in a directory that no longer exists in the source tree (`src/Solutions`), and lists as the latest supported version Visual Studio 2010, when the only solution now in the source tree is in the Visual Studio 2012 format.

The documentation is [1.x](https://github.com/elmah/Elmah/commits/1x) since [`src\Solutions` is still valid there with 2010 the latest supported version](https://github.com/elmah/Elmah/tree/6861de61ddf80000e7204cd976418bd771921ccc/src/Solutions). The real issue is that the docs appear out of date with respect to 2.0.

**Comment by ThomasArdal** [comment]
Plan to look at this Thursday (March 10)

**Comment by atifaziz** [comment]
@ThomasArdal I'm going to hold you to that date! :laughing: 

I think the best approach would be to break out the existing doc in 2 sections with instructions to compile 1.x (already there) and 2.0 from sources.

I'm planning a 1.2 SP 3 release that may simplify the building instructions further as I'll be dropping .NET 1.x builds. I'll try and do that before Thursday but don't hold me to it. :wink:

**Comment by ThomasArdal** [comment]
That sounds awesome :smile:

**Comment by ThomasArdal** [comment]
@atifaziz Isn't this already done?

**Comment by atifaziz** [comment]
@ThomasArdal What makes you think it is? There's been no PR against it that closes it.

**Comment by ThomasArdal** [comment]
@atifaziz https://github.com/elmah/www/pull/31?

**Comment by atifaziz** [comment]
Right, then. Closed. :)
