### ISSUE TITLE
Add reference to elmah.github.io home page

### ISSUE THREAD

**Issue by JavaScriptDude** [elmah/www#32]
I got to the elmah home page on google code and there was no warning that you have migrated over to github. Please add a bold warning to direct users here. I suggest adding a warning banner to other pages in google code such as download so that users don't spin their wheels trying to figure out why they can't download.

**Comment by ThomasArdal** [comment]
I don't know if it is possible to update google code still. @atifaziz knows for sure.

**Comment by atifaziz** [comment]
Done & hopefully this makes it clearer…

![image](https://cloud.githubusercontent.com/assets/20511/19811859/852935b8-9d33-11e6-80b3-c6027cae3eaf.png)

**Comment by JavaScriptDude** [comment]
Perfect. Thanks!
