### ISSUE TITLE
When will elmah support .net core?

### ISSUE THREAD

**Issue by milla** [elmah/www#33]
We're now in porting to .net core for our project. We're finding alternatives of elmah for our project, as now elmah for .net core has not yet rolled out. Since we still have some features waiting for .net core 1.2.0 which is planned around spring next year, so we're using .net core project and framework 4.6.1, does elmah also have plan to roll out .net core version? if do, when? 

Thanks, Elaine

**Comment by atifaziz** [comment]
See elmah/Elmah#407
