### ISSUE TITLE
Link to DotNetSlackers Article is broken

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [elmah/www#34]
https://elmah.github.io/a/mvc/ has references :
"For detailed installation instructions look at the DotNetSlackers Article."
and" There are already excellent (and more detailed) articles." to the link http://dotnetslackers.com/articles/aspnet/ErrorLoggingModulesAndHandlers.aspx
But site http://dotnetslackers.com/ doesn't work.

**Comment by atifaziz** [comment]
Looks like the web site is down at the moment and hopefully that's just temporary. Meanwhile, you could could use either of the following links:

- [dotnetslackers.com article as archived by Wayback Machine](http://web.archive.org/web/20161019071317/http://dotnetslackers.com/articles/aspnet/ErrorLoggingModulesAndHandlers.aspx)
- [Article wiki copy archived on code.google.com](https://code.google.com/archive/p/elmah/wikis/DotNetSlackersArticle.wiki)

**Comment by ThomasArdal** [comment]
@atifaziz The broken link works now. Maybe just close this one?

**Comment by michael-freidgeim-webjet** [comment]
Yes, and  there are 2 backup links.
